[
build
]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "build"

[
build.environment
]
  NODE_VERSION = "16"

[[
redirects
]]
  from = "/*"
  to = "/index.html"
  status = 200